// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuEnvioSeguro.API.Data;

#nullable disable

namespace SuEnvioSeguro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuEnvioSeguro.API.Models.Envio", b =>
                {
                    b.Property<string>("CodigoEnvio")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescripcionContenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionEnvio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsDelicado")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipioDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<float>("ValorNetoEnvio")
                        .HasColumnType("real");

                    b.HasKey("CodigoEnvio");

                    b.HasIndex("CodigoFactura");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("SuEnvioSeguro.API.Models.Factura", b =>
                {
                    b.Property<string>("CodigoFactura")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClienteDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClienteDocumentoIdentidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<float>("PorcentajeIVA")
                        .HasColumnType("real");

                    b.Property<float>("TotalAPagar")
                        .HasColumnType("real");

                    b.Property<string>("UsuarioDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioDocumentoIdentidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("ValorNeto")
                        .HasColumnType("real");

                    b.HasKey("CodigoFactura");

                    b.HasIndex("ClienteDocumento");

                    b.HasIndex("ClienteDocumentoIdentidad");

                    b.HasIndex("UsuarioDocumento");

                    b.HasIndex("UsuarioDocumentoIdentidad");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("SuEnvioSeguro.API.Models.Persona", b =>
                {
                    b.Property<string>("DocumentoIdentidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoIdentidad");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SuEnvioSeguro.API.Models.Cliente", b =>
                {
                    b.HasBaseType("SuEnvioSeguro.API.Models.Persona");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("SuEnvioSeguro.API.Models.Usuario", b =>
                {
                    b.HasBaseType("SuEnvioSeguro.API.Models.Persona");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("SuEnvioSeguro.API.Models.Envio", b =>
                {
                    b.HasOne("SuEnvioSeguro.API.Models.Factura", "Factura")
                        .WithMany("Envios")
                        .HasForeignKey("CodigoFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SuEnvioSeguro.API.Models.Factura", b =>
                {
                    b.HasOne("SuEnvioSeguro.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuEnvioSeguro.API.Models.Cliente", null)
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteDocumentoIdentidad");

                    b.HasOne("SuEnvioSeguro.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioDocumento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SuEnvioSeguro.API.Models.Usuario", null)
                        .WithMany("FacturasGeneradas")
                        .HasForeignKey("UsuarioDocumentoIdentidad");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SuEnvioSeguro.API.Models.Factura", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("SuEnvioSeguro.API.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("SuEnvioSeguro.API.Models.Usuario", b =>
                {
                    b.Navigation("FacturasGeneradas");
                });
#pragma warning restore 612, 618
        }
    }
}
